// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqjrOI0Pp6nrDYrZBvxvfQDjspGVbzCD0',
    appId: '1:1054522879949:web:4153e680e82e0c53f51e84',
    messagingSenderId: '1054522879949',
    projectId: 'cartravk',
    authDomain: 'cartravk.firebaseapp.com',
    databaseURL: 'https://cartravk-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cartravk.appspot.com',
    measurementId: 'G-1TBLCLKJ7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCtuj5R1ubLglx2EYZll935AM1YQvaSQI',
    appId: '1:1054522879949:android:f8c1a0f555d8dcfef51e84',
    messagingSenderId: '1054522879949',
    projectId: 'cartravk',
    databaseURL: 'https://cartravk-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cartravk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjX0d_9TnawZ_icocPdL5EsyNzls7X-SI',
    appId: '1:1054522879949:ios:0dad4ad14981ada2f51e84',
    messagingSenderId: '1054522879949',
    projectId: 'cartravk',
    databaseURL: 'https://cartravk-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cartravk.appspot.com',
    iosBundleId: 'but.itu.ituCartrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjX0d_9TnawZ_icocPdL5EsyNzls7X-SI',
    appId: '1:1054522879949:ios:6fae288b43aa7d72f51e84',
    messagingSenderId: '1054522879949',
    projectId: 'cartravk',
    databaseURL: 'https://cartravk-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cartravk.appspot.com',
    iosBundleId: 'but.itu.ituCartrack.RunnerTests',
  );
}
